/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication20;
import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author 068787845
 */
public class TeacherFrame extends javax.swing.JFrame {
    String password= "teacher1";
    File student = new File("student.txt");
    /**
     * Creates new form TeacherFrame
     */
    public TeacherFrame() {
        initComponents();
        logoutButton.setVisible(false);
        addClassButton.setVisible(false);
        addInstrumentButton.setVisible(false);
        historyButton.setVisible(false);
        signedOutButton.setVisible(false);
        textField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherPanel1 = new org.netbeans.modules.form.InvalidComponent();
        teacherPanel2 = new org.netbeans.modules.form.InvalidComponent();
        addClassButton = new javax.swing.JButton();
        addInstrumentButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        signedOutButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        pWordLabel = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        pWordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addClassButton.setText("Add Class");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        addInstrumentButton.setText("Add Instrument");
        addInstrumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstrumentButtonActionPerformed(evt);
            }
        });

        historyButton.setText("History");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        signedOutButton.setText("Signed Out");
        signedOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signedOutButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("LOG OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        pWordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pWordLabel.setText("Please enter the teacher password.");

        textField.setPreferredSize(new java.awt.Dimension(150, 25));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        pWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherPanel2Layout = new javax.swing.GroupLayout(teacherPanel2);
        teacherPanel2.setLayout(teacherPanel2Layout);
        teacherPanel2Layout.setHorizontalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addInstrumentButton)
                            .addGroup(teacherPanel2Layout.createSequentialGroup()
                                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signedOutButton)
                                    .addComponent(historyButton))
                                .addGap(102, 102, 102)
                                .addComponent(pWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(219, Short.MAX_VALUE))
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addComponent(addClassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addGap(18, 18, 18))))
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(pWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        teacherPanel2Layout.setVerticalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(teacherPanel2Layout.createSequentialGroup()
                        .addGroup(teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addClassButton)
                            .addComponent(logoutButton))
                        .addGap(18, 18, 18)
                        .addComponent(addInstrumentButton)
                        .addGap(18, 18, 18)
                        .addComponent(historyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signedOutButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teacherPanel1Layout = new javax.swing.GroupLayout(teacherPanel1);
        teacherPanel1.setLayout(teacherPanel1Layout);
        teacherPanel1Layout.setHorizontalGroup(
            teacherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        teacherPanel1Layout.setVerticalGroup(
            teacherPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordFieldActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        pWordField.setVisible(true);
        pWordField.setText("");
        pWordLabel.setVisible(true);
        loginButton.setVisible(true);
        logoutButton.setVisible(false);
        addClassButton.setVisible(false);
        addInstrumentButton.setVisible(false);
        historyButton.setVisible(false);
        signedOutButton.setVisible(false);
        textField.setVisible(false);
        pWordLabel.setText("Please enter the teacher password.");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void signedOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signedOutButtonActionPerformed
        if(signedOutButton.getText().equals("Signed Out")){
            addInstrumentButton.setVisible(false);
            historyButton.setVisible(false);
            signedOutButton.setVisible(false);
            addClassButton.setText("Back");
        }
    }//GEN-LAST:event_signedOutButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        if(historyButton.getText().equals("History")){
            addInstrumentButton.setVisible(false);
            historyButton.setVisible(false);
            signedOutButton.setVisible(false);
            addClassButton.setText("Back");
        }
    }//GEN-LAST:event_historyButtonActionPerformed

    private void addInstrumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstrumentButtonActionPerformed
        if(addInstrumentButton.getText().equals("Add Instrument")){
            addInstrumentButton.setVisible(false);
            historyButton.setVisible(false);
            signedOutButton.setVisible(false);
            addClassButton.setText("Back");
        }
    }//GEN-LAST:event_addInstrumentButtonActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        //when acting as the add class button
        if(addClassButton.getText().equals("Add Class")){
            addInstrumentButton.setVisible(false);
            historyButton.setVisible(false);
            signedOutButton.setVisible(false);
            textField.setVisible(true);
            pWordLabel.setVisible(true);
            addClassButton.setText("Back");
            pWordLabel.setText("Print file name.");
            Scanner readClass= new Scanner(textField.getText());
            while(readClass.hasNextLine()){

            }

        }
        //when acting as the back button
        else{
            logoutButton.setVisible(true);
            addClassButton.setVisible(true);
            addInstrumentButton.setVisible(true);
            historyButton.setVisible(true);
            signedOutButton.setVisible(true);
            textField.setVisible(false);
            addClassButton.setText("Add Class");
        }
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(pWordField.getText().equals(password)){
            pWordField.setVisible(false);
            pWordLabel.setVisible(false);
            loginButton.setVisible(false);
            logoutButton.setVisible(true);
            addClassButton.setVisible(true);
            addInstrumentButton.setVisible(true);
            historyButton.setVisible(true);
            signedOutButton.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Password is incorrect. Please try again.");
            pWordField.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addInstrumentButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField pWordField;
    private javax.swing.JLabel pWordLabel;
    private javax.swing.JButton signedOutButton;
    private org.netbeans.modules.form.InvalidComponent teacherPanel1;
    private org.netbeans.modules.form.InvalidComponent teacherPanel2;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
